# Generated by Django 5.2.14 on 2026-05-30 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='produto/')),
                ('slug', models.SlugField(unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalhes', models.TextField()),
                ('quantidade', models.IntegerField(default=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
