# Generated by Django 5.2.14 on 2026-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojavirtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
